#!/bin/sh
# Copyright (c) 2012-2016 Codenvy, S.A., Red Hat, Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Codenvy, S.A. - initial API and implementation
#
# This file is invoked when the che-file container is started.
# Responsible for launching Node server with two parameters:
#   - Location of the che-file logic code, in ../lib/che.js
#   - The che-file command [init, up]

cd $1
/user/bin/env node $(dirname "$0")/../lib/che.js $2